### PR TITLE
Asynchronous prefetching of data

### PR DESCRIPTION
**Pull request by MaxiBoether**
We add an additional thread to load data from the selector in order to hide the latency of data transfer from selector during training.

Solves #175.

### CODE REVIEW

**Review by fotstrt — APPROVED** [review]
Looks great!

**Review by francescodeaglio — APPROVED** [review]
Looks good to me!

**Comment by MaxiBoether** [comment]
Note: This PR is on hold until we can measure the impact of this. We cannot be sure the current implementation here helps since we use multithreading. It _should_ help, since after  `yield` in the generator, we should be able to switch in the prefetch thread in the worker process, but who in the world understands the intricacies of Python multithreading

**Comment by MaxiBoether** [comment]
Closing due to #301

**Pull request closed without merging**
