### PR TITLE
More robust gRPC connections, using `tenacity` where possible

### PR DESCRIPTION
**Pull request by MaxiBoether**
Sometimes, we face outages/random disconnections during training. This fixes it in places where I encountered it last night. I tried to integrate `tenacity` as suggested by @robinholzi, but it's not always possible since the retry logic involves keeping track of already done work, which I don't want to put into class state

Part 6/n of porting over SIGMOD changes.

### CODE REVIEW

**Comment by robinholzi** [comment]
Not fully what the problem with partial result states is, but have you considered using [retry contexts](https://tenacity.readthedocs.io/en/latest/#retrying-code-block)?

**Comment by MaxiBoether** [comment]
> @MaxiBoether Not fully what the problem with partial result states is, but have you considered using [retry contexts](https://tenacity.readthedocs.io/en/latest/#retrying-code-block)?

Ah, nope. I guess I can refactor the code to retry contexts then

**Comment by MaxiBoether** [comment]
> @MaxiBoether Not fully what the problem with partial result states is, but have you considered using [retry contexts](https://tenacity.readthedocs.io/en/latest/#retrying-code-block)?

Thanks for suggesting that. I adapted the code. However, I needed to manually catch and reraise exceptions sometimes because I find their callback system to be quite ugly in object-oriented contexts (we need to write a static function that recovers `self` out of args[0] etc). I think this actually looks better than using callbacks, and it allows for easier logging with our logging infra. The retry logic itself is still more hidden now :)

**Review by robinholzi — APPROVED** [review]
Thanks for the refactoring! Looks good now :)

**Pull request merged**
