### PR TITLE
feat: Add `codecov`

### PR DESCRIPTION
**Pull request by robinholzi**
# Motivation

Let's integrate codecov to get rid of the bulky coverage messages

### CODE REVIEW

**Comment by robinholzi** [comment]
@MaxiBoether Can you get a `CODECOV_TOKEN` from https://app.codecov.io/gh/eth-easl/modyn/settings and store it as a repository secret?

**Comment by MaxiBoether** [comment]
> @MaxiBoether Can you get a `CODECOV_TOKEN` from https://app.codecov.io/gh/eth-easl/modyn/settings and store it as a repository secret?

Will do tomorrow! Thank you!!

**Comment by MaxiBoether** [comment]
> > @MaxiBoether Can you get a `CODECOV_TOKEN` from https://app.codecov.io/gh/eth-easl/modyn/settings and store it as a repository secret?
> 
> Will do tomorrow! Thank you!!

Done

**Comment by robinholzi** [comment]
Nice @MaxiBoether , maybe you can generate a [badge](https://docs.codecov.com/docs/status-badges) and add it to the README, then we are ready to merge :)

**Review by MaxiBoether — APPROVED** [review]
Nice, thanks! I also added a badge to the README :)

**Comment by MaxiBoether** [comment]
Just fyi, we actually also have C++ coverage, but something there is broken and I never found the time to investigate this. In any case, not that important...

**Comment by robinholzi** [comment]
> Just fyi, we actually also have C++ coverage, but something there is broken and I never found the time to investigate this. In any case, not that important...

Unfortunately, I'm not extremely proficient with cpp tooling, and currently don't have the time to dive into that😅

**Pull request merged**
